name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - test-branch
  pull_request:
    branches:
      - main

jobs: # the things being executed
  build:  # the name of your status check
    name: Lint Code Base
    runs-on: ubuntu-latest  # which device on Github's server that you are running the Actions on
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_HTML: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: .*docs/.*

  #test: # the name of your status check, will become important when you do branch protection
  #  name: Test Code Base
  #  runs-on: ubuntu-latest # which device on Github's server that you are running the Actions on
  #  steps:
  #    - name: Checkout Code
  #      uses: actions/checkout@v4 # using version 4 of Actions
  #    - name: Install Dependencies
  #      run: npm install
  #    - name: Unit Test
  #      run: npm run test:unit # unit tests
  #    - name: E2E Test
  #      run: npm run test:e2e # e2e tests
 
  test:
    name: Test Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Fetch Code Climate Test Reporter Binary
        run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - name: Make Test Reporter Executable
        run: chmod +x ./cc-test-reporter
      - name: Run Code Climate Before Build
        run: ./cc-test-reporter before-build
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      - name: Run Unit Tests with Coverage
        run: npm run coverage:unit
      - name: Run E2E Tests with Coverage
        run: npm run coverage:e2e
      - name: Format Unit Test Coverage
        run: ./cc-test-reporter format-coverage --output coverage/unit/codeclimate.unit.json --input-type lcov coverage/unit/lcov.info
      - name: Format E2E Test Coverage
        run: ./cc-test-reporter format-coverage --output coverage/e2e/codeclimate.e2e.json --input-type lcov coverage/e2e/lcov.info
      - name: Sum Coverage
        run: ./cc-test-reporter sum-coverage coverage/unit/codeclimate.unit.json coverage/e2e/codeclimate.e2e.json --output coverage/codeclimate.json
      - name: Upload Combined Coverage
        run: ./cc-test-reporter upload-coverage --input coverage/codeclimate.json
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  generate-docs:
    name: Generate JSDocs
    runs-on: ubuntu-latest # which device on Github's server that you are running the Actions on
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # using version 4 of Actions
      - name: Generate JSDocs
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          recurse: true
          output_dir: ./docs
          config_file: jsdoc.json
          front_page: ./docs/backend-documentation.md