name: CI/CD Pipeline

on: [push, pull_request] 

jobs: # the things being executed
  build:  # the name of your status check
    name: Lint Code Base
    runs-on: ubuntu-latest  # which device on Github's server that you are running the Actions on
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_HTML: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: .*docs/.*
 
  test:
    name: Test Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: start server
        run: npm start & npx wait-on http://localhost:3000
        background: true
      - name: Fetch Code Climate Test Reporter Binary
        run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - name: Make Test Reporter Executable
        run: chmod +x ./cc-test-reporter
      - name: Run Code Climate Before Build
        run: ./cc-test-reporter before-build
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      - name: Run Unit Tests with Coverage
        run: npm run coverage:unit
      - name: Run E2E Tests
        run: npm run test:e2e
      - name: Run Code Climate After Build
        run: ./cc-test-reporter after-build --exit-code $? -t lcov -r ${{ secrets.CC_TEST_REPORTER_ID }}
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  generate-docs:
    name: Generate JSDocs
    runs-on: ubuntu-latest # which device on Github's server that you are running the Actions on
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # using version 4 of Actions
      - name: Generate JSDocs
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          recurse: true
          output_dir: ./docs
          config_file: jsdoc.json
          front_page: ./docs/backend-documentation.md